# Generated by Django 4.0.4 on 2022-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_type',
            field=models.CharField(choices=[('Physician', 'Physician'), ('PA', 'PA'), ('NP', 'NP')], max_length=100),
        ),
    ]
