# Generated by Django 4.0.4 on 2022-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='photo_url',
            field=models.TextField(default='https://i.imgur.com/3kkOeEY.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.TextField(default='https://i.imgur.com/3kkOeEY.jpg', null=True),
        ),
    ]
