# Generated by Django 4.0.4 on 2022-05-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0002_alter_provider_photo_url_alter_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
