# Generated by Django 4.0.4 on 2022-05-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0002_user_is_provider_alter_user_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='systolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pressr.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_type',
            field=models.CharField(choices=[('Physician', 'Physician'), ('PA', 'PA'), ('NP', 'NP')], max_length=100, null=True),
        ),
    ]
