# Generated by Django 4.0.4 on 2022-05-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0005_alter_user_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo_url', models.TextField(null=True)),
                ('provider_type', models.CharField(blank=True, choices=[('Physician', 'Physician'), ('PA', 'PA'), ('NP', 'NP')], max_length=101, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provider_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_of_comment',
            field=models.CharField(choices=[('User', 'User'), ('Provider', 'Provider')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pressr.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pressr.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pressr.provider'),
        ),
    ]
