# Generated by Django 4.0.4 on 2022-05-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0006_provider_remove_user_is_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pressr.provider'),
        ),
    ]
