# Generated by Django 4.0.4 on 2022-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0007_alter_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('Physician', 'Physician'), ('PA', 'PA'), ('NP', 'NP')], max_length=100, null=True),
        ),
    ]
