# Generated by Django 4.0.4 on 2022-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressr', '0009_alter_provider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=101),
        ),
    ]
